# Generated by Django 2.1.5 on 2019-03-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_blog_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=51)),
                ('category_summury', models.CharField(max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='blog_news',
            name='url_slug',
            field=models.CharField(default='default', max_length=31),
        ),
        migrations.AddField(
            model_name='blog_news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Store.Categories'),
        ),
    ]
