# Generated by Django 2.1.5 on 2019-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190318_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(default='all', max_length=31),
        ),
    ]
