# Generated by Django 2.1.5 on 2019-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190408_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='news_category',
        ),
        migrations.AddField(
            model_name='product',
            name='news_category',
            field=models.ManyToManyField(to='Store.Categories'),
        ),
    ]
